### PR TITLE
Bump resolvers to lts-8.8

### PR DESCRIPTION
**Pull request by vaibhavsagar**

### CODE REVIEW

**Comment by abarbu** [comment]
I'm so tempted to kill off all of the support packages and merge them into the main one. It would also be far easier for users.

**Comment by vaibhavsagar** [comment]
It takes forever to compile though :frowning:

**Comment by abarbu** [comment]
That's true. It's just one file though and it's not so bad when you add in --fast.
Maybe making --fast the default is enough given that there's nothing high-performance here. I suspect that file is slow because of vinyl but I'm not sure.

**Comment by vaibhavsagar** [comment]
This might not be the best place for this, but I was wondering if it might be better to split `ihaskell-display` off into its own module and have both ihaskell and the display modules depend on that instead? That way we only have to get one small module into the global cabal/stack pkgdb and user-defined IHaskellDisplay instances become easy.

**Comment by abarbu** [comment]
I've been thinking about the solution to this as well.

That would only help if someone wanted to have ihaskell-display instances without actually installing ihaskell; and I'm not sure this is a common usecase. Is it? Upstream packages aren't going to depend on ihaskell-display even if it's small regradless (and they shouldn't). Also, if they start to depend on it, this would become a nightmare; a change in ihaskell would require changes in lots of other packages totally unrelated to it.

I think the far more common usecase is that someone just wants to use ihaskell and wants it to work out of the box. Then the next most common usecase is that they want to write some additional instances; which they can and they can easily share even if ihaskell is one repo & one package.

**Pull request merged**
